import 'package:path_provider/path_provider.dart';

import 'models/memory_vector.dart';

// This file will be generated by objectbox_generator
// Run: flutter pub run build_runner build
import '../../objectbox.g.dart';

/// Vector store for semantic search using ObjectBox HNSW
class VectorStore {
  late final Store _store;
  late final Box<MemoryVector> _memoryBox;
  late final Box<ConversationVector> _conversationBox;

  bool _isInitialized = false;

  /// Initialize the ObjectBox store
  Future<void> initialize() async {
    if (_isInitialized) return;

    final dir = await getApplicationDocumentsDirectory();
    final dbPath = '${dir.path}/jarvis_vectors';

    _store = await openStore(directory: dbPath);
    _memoryBox = _store.box<MemoryVector>();
    _conversationBox = _store.box<ConversationVector>();

    _isInitialized = true;
  }

  /// Close the store
  void close() {
    if (_isInitialized) {
      _store.close();
      _isInitialized = false;
    }
  }

  // ============================================
  // Memory Vector Operations
  // ============================================

  /// Store a memory node embedding
  Future<int> storeMemoryVector({
    required String nodeId,
    required String sourceText,
    required List<double> embedding,
  }) async {
    final vector = MemoryVector(
      entityRef: 'node:$nodeId',
      entityType: 'node',
      sourceText: sourceText,
      embedding: embedding,
    );
    return _memoryBox.put(vector);
  }

  /// Get memory vector by node ID
  MemoryVector? getMemoryVector(String nodeId) {
    final query = _memoryBox
        .query(MemoryVector_.entityRef.equals('node:$nodeId'))
        .build();
    final result = query.findFirst();
    query.close();
    return result;
  }

  /// Delete memory vector by node ID
  Future<bool> deleteMemoryVector(String nodeId) async {
    final query = _memoryBox
        .query(MemoryVector_.entityRef.equals('node:$nodeId'))
        .build();
    final result = query.findFirst();
    query.close();

    if (result != null) {
      return _memoryBox.remove(result.id);
    }
    return false;
  }

  /// Semantic search for memory nodes using native HNSW index
  /// Returns node IDs sorted by similarity (most similar first)
  Future<List<SemanticSearchResult>> searchMemoryNodes({
    required List<double> queryEmbedding,
    int limit = 10,
    double? minScore,
  }) async {
    // Convert to float32 list for ObjectBox HNSW query
    final queryVectorF32 = queryEmbedding.map((e) => e.toDouble()).toList();

    // Use ObjectBox native HNSW nearest neighbor search
    // This is much more efficient than manual cosine similarity on large datasets
    final query = _memoryBox
        .query(
          MemoryVector_.embedding.nearestNeighborsF32(queryVectorF32, limit),
        )
        .build();

    final nearestVectors = query.findWithScores();
    query.close();

    final results = <SemanticSearchResult>[];
    for (final result in nearestVectors) {
      final vector = result.object;
      // ObjectBox returns L2 distance, convert to similarity score (0-1)
      // Lower distance = higher similarity
      // Score = 1 / (1 + distance) gives us a 0-1 range
      final distance = result.score;
      final similarityScore = 1 / (1 + distance);

      // Apply minimum score filter
      if (minScore != null && similarityScore < minScore) continue;

      final nodeId = vector.entityRef.replaceFirst('node:', '');
      results.add(SemanticSearchResult(
        entityId: nodeId,
        score: similarityScore,
        sourceText: vector.sourceText,
      ));
    }

    return results;
  }

  // ============================================
  // Conversation Vector Operations
  // ============================================

  /// Store a message embedding
  Future<int> storeConversationVector({
    required String conversationId,
    required String messageId,
    required String content,
    required String role,
    required List<double> embedding,
    DateTime? timestamp,
  }) async {
    final vector = ConversationVector(
      conversationId: conversationId,
      messageId: messageId,
      content: content,
      role: role,
      embedding: embedding,
      timestamp: timestamp,
    );
    return _conversationBox.put(vector);
  }

  /// Get conversation vectors for a specific conversation
  List<ConversationVector> getConversationVectors(String conversationId) {
    final query = _conversationBox
        .query(ConversationVector_.conversationId.equals(conversationId))
        .build();
    final results = query.find();
    query.close();
    return results;
  }

  /// Delete all vectors for a conversation
  Future<int> deleteConversationVectors(String conversationId) async {
    final query = _conversationBox
        .query(ConversationVector_.conversationId.equals(conversationId))
        .build();
    final count = query.remove();
    query.close();
    return count;
  }

  /// Semantic search across all conversations using native HNSW index
  Future<List<SemanticSearchResult>> searchConversations({
    required List<double> queryEmbedding,
    String? conversationId,
    int limit = 10,
    double? minScore,
  }) async {
    final queryVectorF32 = queryEmbedding.map((e) => e.toDouble()).toList();

    // Build query with optional conversation filter and HNSW search
    Query<ConversationVector> query;
    if (conversationId != null) {
      query = _conversationBox
          .query(
            ConversationVector_.conversationId.equals(conversationId) &
            ConversationVector_.embedding.nearestNeighborsF32(queryVectorF32, limit),
          )
          .build();
    } else {
      query = _conversationBox
          .query(
            ConversationVector_.embedding.nearestNeighborsF32(queryVectorF32, limit),
          )
          .build();
    }

    final nearestVectors = query.findWithScores();
    query.close();

    final results = <SemanticSearchResult>[];
    for (final result in nearestVectors) {
      final vector = result.object;
      final distance = result.score;
      final similarityScore = 1 / (1 + distance);

      if (minScore != null && similarityScore < minScore) continue;

      results.add(SemanticSearchResult(
        entityId: vector.messageId,
        score: similarityScore,
        sourceText: vector.content,
        metadata: {
          'conversationId': vector.conversationId,
          'role': vector.role,
          'timestamp': vector.timestamp.toIso8601String(),
        },
      ));
    }

    return results;
  }

  // ============================================
  // Utility Methods
  // ============================================

  /// Get total count of vectors
  int get memoryVectorCount => _memoryBox.count();
  int get conversationVectorCount => _conversationBox.count();

  /// Clear all vectors (for testing/reset)
  Future<void> clearAll() async {
    _memoryBox.removeAll();
    _conversationBox.removeAll();
  }
}

/// Result from semantic search
class SemanticSearchResult {
  final String entityId;
  final double score;
  final String sourceText;
  final Map<String, dynamic>? metadata;

  SemanticSearchResult({
    required this.entityId,
    required this.score,
    required this.sourceText,
    this.metadata,
  });

  @override
  String toString() => 'SemanticSearchResult(id: $entityId, score: ${score.toStringAsFixed(3)})';
}
