// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/vector/models/memory_vector.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3898764361167014473),
    name: 'ConversationVector',
    lastPropertyId: const obx_int.IdUid(7, 6416980958760659961),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3160012266232517777),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1716074321622108445),
        name: 'conversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 8134160783799747004),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 968539290053076826),
        name: 'messageId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 2384001499035957627),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8625069562942921388),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3299076054068671383),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8768158850088651256),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(3, 8253503147984814343),
        hnswParams: obx_int.ModelHnswParams(dimensions: 100),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6416980958760659961),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8858621816669815397),
    name: 'MemoryVector',
    lastPropertyId: const obx_int.IdUid(6, 1703347877656800961),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1239640686923696031),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4155620044547512536),
        name: 'entityRef',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 8160307578604712126),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3121143234799865873),
        name: 'entityType',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 8990521759553571412),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2160920357051459952),
        name: 'sourceText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7075526181754003841),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(6, 3978439764547675141),
        hnswParams: obx_int.ModelHnswParams(dimensions: 100),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1703347877656800961),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 8858621816669815397),
    lastIndexId: const obx_int.IdUid(6, 3978439764547675141),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ConversationVector: obx_int.EntityDefinition<ConversationVector>(
      model: _entities[0],
      toOneRelations: (ConversationVector object) => [],
      toManyRelations: (ConversationVector object) => {},
      getId: (ConversationVector object) => object.id,
      setId: (ConversationVector object, int id) {
        object.id = id;
      },
      objectToFB: (ConversationVector object, fb.Builder fbb) {
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final messageIdOffset = fbb.writeString(object.messageId);
        final contentOffset = fbb.writeString(object.content);
        final roleOffset = fbb.writeString(object.role);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, conversationIdOffset);
        fbb.addOffset(2, messageIdOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addOffset(4, roleOffset);
        fbb.addOffset(5, embeddingOffset);
        fbb.addInt64(6, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final conversationIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final messageIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = ConversationVector(
          id: idParam,
          conversationId: conversationIdParam,
          messageId: messageIdParam,
          content: contentParam,
          role: roleParam,
          embedding: embeddingParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    MemoryVector: obx_int.EntityDefinition<MemoryVector>(
      model: _entities[1],
      toOneRelations: (MemoryVector object) => [],
      toManyRelations: (MemoryVector object) => {},
      getId: (MemoryVector object) => object.id,
      setId: (MemoryVector object, int id) {
        object.id = id;
      },
      objectToFB: (MemoryVector object, fb.Builder fbb) {
        final entityRefOffset = fbb.writeString(object.entityRef);
        final entityTypeOffset = fbb.writeString(object.entityType);
        final sourceTextOffset = fbb.writeString(object.sourceText);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entityRefOffset);
        fbb.addOffset(2, entityTypeOffset);
        fbb.addOffset(3, sourceTextOffset);
        fbb.addOffset(4, embeddingOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entityRefParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final entityTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = MemoryVector(
          id: idParam,
          entityRef: entityRefParam,
          entityType: entityTypeParam,
          sourceText: sourceTextParam,
          embedding: embeddingParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ConversationVector] entity fields to define ObjectBox queries.
class ConversationVector_ {
  /// See [ConversationVector.id].
  static final id = obx.QueryIntegerProperty<ConversationVector>(
    _entities[0].properties[0],
  );

  /// See [ConversationVector.conversationId].
  static final conversationId = obx.QueryStringProperty<ConversationVector>(
    _entities[0].properties[1],
  );

  /// See [ConversationVector.messageId].
  static final messageId = obx.QueryStringProperty<ConversationVector>(
    _entities[0].properties[2],
  );

  /// See [ConversationVector.content].
  static final content = obx.QueryStringProperty<ConversationVector>(
    _entities[0].properties[3],
  );

  /// See [ConversationVector.role].
  static final role = obx.QueryStringProperty<ConversationVector>(
    _entities[0].properties[4],
  );

  /// See [ConversationVector.embedding].
  static final embedding = obx.QueryHnswProperty<ConversationVector>(
    _entities[0].properties[5],
  );

  /// See [ConversationVector.timestamp].
  static final timestamp = obx.QueryDateProperty<ConversationVector>(
    _entities[0].properties[6],
  );
}

/// [MemoryVector] entity fields to define ObjectBox queries.
class MemoryVector_ {
  /// See [MemoryVector.id].
  static final id = obx.QueryIntegerProperty<MemoryVector>(
    _entities[1].properties[0],
  );

  /// See [MemoryVector.entityRef].
  static final entityRef = obx.QueryStringProperty<MemoryVector>(
    _entities[1].properties[1],
  );

  /// See [MemoryVector.entityType].
  static final entityType = obx.QueryStringProperty<MemoryVector>(
    _entities[1].properties[2],
  );

  /// See [MemoryVector.sourceText].
  static final sourceText = obx.QueryStringProperty<MemoryVector>(
    _entities[1].properties[3],
  );

  /// See [MemoryVector.embedding].
  static final embedding = obx.QueryHnswProperty<MemoryVector>(
    _entities[1].properties[4],
  );

  /// See [MemoryVector.createdAt].
  static final createdAt = obx.QueryDateProperty<MemoryVector>(
    _entities[1].properties[5],
  );
}
